import Head from 'next/head'
import Image from 'next/image'
import MyNavbar from '../components/MyNavbar'

export default function Home() {
    return (
        <>
            <style jsx>
                {`
                h2 {
                    color: var(--color-text-primary);
                }
                p {
                    color: var(--color-text-secondary);
                }
                .card {
                    background: var(--color-bg-primary);
                }
                .card-text {
                    color: var(--color-text-secondary);
                }
            `}
            </style>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MyNavbar/>

            <main>

                <div className="container px-4 py-5" id="featured-3">
                    <h2 className="pb-2">Columns with icons</h2>
                    <div className="row g-4 py-5 row-cols-1 row-cols-lg-3">
                        <div className="feature col">
                            <h2>Featured title</h2>
                            <p>Paragraph of text beneath the heading to explain the heading. Well add onto it with another sentence and probably just keep going until we run out of words.</p>
                            <a href="#" className="icon-link">
                                Call to action
                                <svg className="bi" width="1em" height="1em"></svg>
                            </a>
                        </div>
                        <div className="feature col">
                            <h2>Featured title</h2>
                            <p>Paragraph of text beneath the heading to explain the heading. Well add onto it with another sentence and probably just keep going until we run out of words.</p>
                            <a href="#" className="icon-link">
                                Call to action
                                <svg className="bi" width="1em" height="1em"></svg>
                            </a>
                        </div>
                        <div className="feature col">
                            <h2>Featured title</h2>
                            <p>Paragraph of text beneath the heading to explain the heading. Well add onto it with another sentence and probably just keep going until we run out of words.</p>
                            <a href="#" className="icon-link">
                                Call to action
                                <svg className="bi" width="1em" height="1em"></svg>
                            </a>
                        </div>
                    </div>
                </div>

            </main>
        </>
    )
}
